"""empty message

Revision ID: f8a51ee72825
Revises: 3c816e885b90
Create Date: 2023-12-24 04:14:22.754381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a51ee72825'
down_revision = '3c816e885b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.drop_column('descrption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrption', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
